/* aria attributes here https://www.w3.org/TR/wai-aria/rdf_model.svg */
export const ariaRoles = {
  alert: ['A message with important, and usually time-sensitive, information. See related alertdialog and status.'],
  alertdialog: ['A type of dialog that contains an alert message, where initial focus goes to an element within the ' +
  'dialog. See related alert and dialog.'],
  application: ['A region declared as a web application, as opposed to a web document.'],
  article: ['A section of a page that consists of a composition that forms an independent part of a document, page, ' +
  'or site.'],
  banner: ['A region that contains mostly site-oriented content, rather than page-specific content.'],
  button: ['An input that allows for user-triggered actions when clicked or pressed. See related link.'],
  checkbox: ['A checkable input that has three possible values, false, or mixed.'],
  columnheader: ['A cell containing header information for a column.'],
  combobox: ['A presentation of a select; usually similar to a textbox where users can type ahead to select an ' +
  'option, or type to enter arbitrary text as a new item in the list. See related listbox.'],
  command: ['abstract role',
    'A form of widget that performs an action but does not receive input data.'],
  complementary: ['A supporting section of the document, designed to be complementary to the main content at a ' +
  'similar level in the DOM hierarchy, but remains meaningful when separated from the main content.'],
  composite: ['abstract role',
    'A widget that may contain navigable descendants or owned children.'],
  contentinfo: ['A large perceivable region that contains information about the parent document.'],
  definition: ['A definition of a term or concept.'],
  dialog: ['A dialog is an application window that is designed to interrupt the current processing of an application ' +
  'in order to prompt the user to enter information or require a response. See related alertdialog.'],
  directory: ['A list of references to members of a group, such as a static table of contents.'],
  document: ['A region containing related information that is declared as document content, as opposed to a web ' +
  'application.'],
  form: ['A landmark region that contains a collection of items and objects that, as a whole, combine to create a ' +
  'form. See related search.'],
  grid: ['A grid is an interactive control which contains cells of tabular data arranged in rows and columns, like a ' +
  'table.'],
  gridcell: ['A cell in a grid or treegrid.'],
  group: ['A set of user interface objects which are not intended to be included in a page summary or table of ' +
  'contents by assistive technologies.'],
  heading: ['A heading for a section of the page.'],
  img: ['A container for a collection of elements that form an image.'],
  input: ['abstract role',
    'A generic type of widget that allows user input.'],
  landmark: ['abstract role',
    'A region of the page intended as a navigational landmark.'],
  link: ['An interactive reference to an internal or external resource that, when activated, causes the user agent ' +
  'to navigate to that resource. See related button.'],
  list: ['A group of non-interactive list items. See related listbox.'],
  listbox: ['A widget that allows the user to select one or more items from a list of choices. See related combobox ' +
  'and list.'],
  listitem: ['A single item in a list or directory.'],
  log: ['A type of live region where new information is added in meaningful order and old information may disappear. ' +
  'See related marquee.'],
  main: ['The main content of a document.'],
  marquee: ['A type of live region where non-essential information changes frequently. See related log.'],
  math: ['Content that represents a mathematical expression.'],
  menu: ['A type of widget that offers a list of choices to the user.'],
  menubar: ['A presentation of menu that usually remains visible and is usually presented horizontally.'],
  menuitem: ['An option in a set of choices contained by a menu or menubar.'],
  menuitemcheckbox: ['A menuitem with a checkable state whose possible values are true, false, or mixed.'],
  menuitemradio: ['A checkable menuitem in a set of elements with role menuitemradio, only one of which can be ' +
  'checked at a time.'],
  navigation: ['A collection of navigational elements (usually links) for navigating the document or related ' +
  'documents.'],
  note: ['A section whose content is parenthetic or ancillary to the main content of the resource.'],
  option: ['A selectable item in a select list.'],
  presentation: ['An element whose implicit native role semantics will not be mapped to the accessibility API.'],
  progressbar: ['An element that displays the progress status for tasks that take a long time.'],
  radio: ['A checkable input in a group of radio roles, only one of which can be checked at a time.'],
  radiogroup: ['A group of radio buttons.'],
  range: ['abstract role',
    'An input representing a range of values that can be set by the user.'],
  region: ['A large perceivable section of a web page or document, that is important enough to be included in a page ' +
  'summary or table of contents, for example, an area of the page containing live sporting event statistics.'],
  roletype: ['abstract role',
    'The base role from which all other roles in this taxonomy inherit.'],
  row: ['A row of cells in a grid.'],
  rowgroup: ['A group containing one or more row elements in a grid.'],
  rowheader: ['A cell containing header information for a row in a grid.'],
  scrollbar: ['A graphical object that controls the scrolling of content within a viewing area, regardless of ' +
  'whether the content is fully displayed within the viewing area.'],
  search: ['A landmark region that contains a collection of items and objects that, as a whole, combine to create a ' +
  'search facility. See related form.'],
  section: ['abstract role',
    'A renderable structural containment unit in a document or application.'],
  sectionhead: ['abstract role',
    'A structure that labels or summarizes the topic of its related section.'],
  select: ['abstract role',
    'A form widget that allows the user to make selections from a set of choices.'],
  separator: ['A divider that separates and distinguishes sections of content or groups of menuitems.'],
  slider: ['A user input where the user selects a value from within a given range.'],
  spinbutton: ['A form of range that expects the user to select from among discrete choices.'],
  status: ['A container whose content is advisory information for the user but is not important enough to justify an ' +
  'alert, often but not necessarily presented as a status bar. See related alert.'],
  structure: ['abstract role',
    'A document structural element.'],
  tab: ['A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user.'],
  tablist: ['A list of tab elements, which are references to tabpanel elements.'],
  tabpanel: ['A container for the resources associated with a tab, where each tab is contained in a tablist.'],
  textbox: ['Input that allows free-form text as its value.'],
  timer: ['A type of live region containing a numerical counter which indicates an amount of elapsed time from a ' +
  'start point, or the time remaining until an end point.'],
  toolbar: ['A collection of commonly used function buttons or controls represented in compact visual form.'],
  tooltip: ['A contextual popup that displays a description for an element.'],
  tree: ['A type of list that may contain sub-level nested groups that can be collapsed and expanded.'],
  treegrid: ['A grid whose rows can be expanded and collapsed in the same manner as for a tree.'],
  treeitem: ['An option item of a tree. This is an element within a tree that may be expanded or collapsed if it ' +
  'contains a sub-level group of treeitem elements.'],
  widget: ['abstract role',
    'An interactive component of a graphical user interface (GUI).'],
  window: ['abstract role',
    'A browser or application window.'],
}

const five = true
export const html5 = {
  a: 'Defines a hyperlink',
  abbr: 'Defines an abbreviation or an acronym',
  address: 'Defines contact information for the author/owner of a document',
  area: 'Defines an area inside an image-map',
  article: { five, d: 'Defines an article' },
  aside: { five, d: 'Defines content aside from the page content' },
  audio: { five, d: 'Defines sound content' },
  b: 'Defines bold text',
  base: 'Specifies the base URL/target for all relative URLs in a document',
  bdi: {
    five,
    d: 'Isolates a part of text that might be formatted in a different direction from other text outside it'
  },
  bdo: 'Overrides the current text direction',
  blockquote: 'Defines a section that is quoted from another source',
  body: 'Defines the document body',
  br: 'Defines a single line break',
  button: 'Defines a clickable button',
  canvas: { five, d: 'Used to draw graphics, on the fly, via scripting (usually JavaScript)' },
  caption: 'Defines a table caption',
  cite: 'Defines the title of a work',
  code: 'Defines a piece of computer code',
  col: 'Specifies column properties for each column within a <colgroup> element ',
  colgroup: 'Specifies a group of one or more columns in a table for formatting',
  datalist: { five, d: 'Specifies a list of pre-defined options for input controls' },
  dd: 'Defines a description/value of a term in a description list',
  del: 'Defines text that has been deleted from a document',
  details: { five, d: 'Defines additional details that the user can view or hide' },
  dfn: 'Represents the defining instance of a term',
  dialog: { five, d: 'Defines a dialog box or window' },
  div: 'Defines a section in a document',
  dl: 'Defines a description list',
  dt: 'Defines a term/name in a description list',
  em: 'Defines emphasized text ',
  embed: { five, d: 'Defines a container for an external (non-HTML) application' },
  fieldset: 'Groups related elements in a form',
  figcaption: { five, d: 'Defines a caption for a <figure> element' },
  figure: { five, d: 'Specifies self-contained content' },
  footer: { five, d: 'Defines a footer for a document or section' },
  form: 'Defines an HTML form for user input',
  h1: 'to <h6> Defines HTML headings',
  head: 'Defines information about the document',
  header: { five, d: 'Defines a header for a document or section' },
  hr: 'Defines a thematic change in the content',
  html: 'Defines the root of an HTML document',
  i: 'Defines a part of text in an alternate voice or mood',
  iframe: 'Defines an inline frame',
  img: 'Defines an image',
  input: 'Defines an input control',
  ins: 'Defines a text that has been inserted into a document',
  kbd: 'Defines keyboard input',
  keygen: { five, d: 'Defines a key-pair generator field (for forms)' },
  label: 'Defines a label for an <input> element',
  legend: 'Defines a caption for a <fieldset> element',
  li: 'Defines a list item',
  link: 'Defines the relationship between a document and an external resource (most used to link to style sheets)',
  main: { five, d: 'Specifies the main content of a document' },
  map: 'Defines a client-side image-map',
  mark: { five, d: 'Defines marked/highlighted text' },
  menu: 'Defines a list/menu of commands',
  menuitem: { five, d: 'Defines a command/menu item that the user can invoke from a popup menu' },
  meta: 'Defines metadata about an HTML document',
  meter: { five, d: 'Defines a scalar measurement within a known range (a gauge)' },
  nav: { five, d: 'Defines navigation links' },
  noscript: 'Defines an alternate content for users that do not support client-side scripts',
  object: 'Defines an embedded object',
  ol: 'Defines an ordered list',
  optgroup: 'Defines a group of related options in a drop-down list',
  option: 'Defines an option in a drop-down list',
  output: { five, d: 'Defines the result of a calculation' },
  p: 'Defines a paragraph',
  param: 'Defines a parameter for an object',
  picture: { five, d: 'Defines a container for multiple image resources' },
  pre: 'Defines preformatted text',
  progress: { five, d: 'Represents the progress of a task' },
  q: 'Defines a short quotation',
  rp: { five, d: 'Defines what to show in browsers that do not support ruby annotations' },
  rt: { five, d: 'Defines an explanation/pronunciation of characters (for East Asian typography)' },
  ruby: { five, d: 'Defines a ruby annotation (for East Asian typography)' },
  s: 'Defines text that is no longer correct',
  samp: 'Defines sample output from a computer program',
  script: 'Defines a client-side script',
  section: { five, d: 'Defines a section in a document' },
  select: 'Defines a drop-down list',
  small: 'Defines smaller text',
  source: { five, d: 'Defines multiple media resources for media elements (<video> and <audio>)' },
  span: 'Defines a section in a document',
  strong: 'Defines important text',
  style: 'Defines style information for a document',
  sub: 'Defines subscripted text',
  summary: { five, d: 'Defines a visible heading for a <details> element' },
  sup: 'Defines superscripted text',
  table: 'Defines a table',
  tbody: 'Groups the body content in a table',
  td: 'Defines a cell in a table',
  textarea: 'Defines a multiline input control (text area)',
  tfoot: 'Groups the footer content in a table',
  th: 'Defines a header cell in a table',
  thead: 'Groups the header content in a table',
  time: { five, d: 'Defines a date/time' },
  title: 'Defines a title for the document',
  tr: 'Defines a row in a table',
  track: { five, d: 'Defines text tracks for media elements (<video> and <audio>)' },
  u: 'Defines text that should be stylistically different from normal text',
  ul: 'Defines an unordered list',
  var: 'Defines a variable',
  video: { five, d: 'Defines a video or movie' },
  wbr: { five, d: 'Defines a possible line-break' },
}
